command_timeout = 10000

[git_branch]
always_show_remote = true
disabled = false

[git_metrics] 
disabled = false

[git_status]
disabled = false

[directory]
style = "bright-purple"
format = "[>]($style) [$path]($style)[$read_only]($read_only_style) "

[sudo]
disabled = false

[time]
disabled = false

[status]
format = "[⚠️ ${symbol}${signal_name}${status}]($style)"
disabled = false

[memory_usage]
disabled = false
threshold = 0
style = "bold cyan"
format = "[${ram}( => ${ram_pct})]($style) [>]($style) "

[username]
disabled = false
show_always = true
format = "[@${user}]($style) "

[nodejs]
detect_extensions = ["js", "mjs", "cjs", "jsx", "ts", "mts", "cts", "tsx"]

