[git_branch]
always_show_remote = true

[git_commit]
commit_hash_length = 8
style = "bold orange"
disabled = false

[git_state]
disabled = false

[git_metrics] 
disabled = false

[git_status]
disabled = false

[nodejs]
disabled = false

[shell]
disabled = false

[sudo]
disabled = false

[time]
disabled = false

[username]
disabled = false

[directory]
disabled = false

[status]
disabled = false

[jobs]
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
