return {
  -- "ThePrimeagen/harpoon",
  -- branch = "harpoon2",
  -- dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
  -- event = "VeryLazy",
  -- config = function()
  --   local harpoon = require "harpoon"
  --   harpoon:setup()
  --   local key = vim.keymap
  --   key.set("n", "<leader>aa", function()
  --     harpoon:list():add()
  --   end)
  --   key.set("n", "<leader>a1", function()
  --     harpoon:list():select(1)
  --   end)
  --   key.set("n", "<leader>a2", function()
  --     harpoon:list():select(2)
  --   end)
  --   key.set("n", "<leader>a3", function()
  --     harpoon:list():select(3)
  --   end)
  --   key.set("n", "<leader>a4", function()
  --     harpoon:list():select(4)
  --   end)
  --   key.set("n", "<C-S-P>", function()
  --     harpoon:list():prev()
  --   end)
  --   key.set("n", "<C-S-N>", function()
  --     harpoon:list():next()
  --   end)
  --   local conf = require("telescope.config").values
  --   local function toggle_telescope(harpoon_files)
  --     local file_paths = {}
  --     for _, item in ipairs(harpoon_files.items) do
  --       table.insert(file_paths, item.value)
  --     end
  --
  --     require("telescope.pickers")
  --       .new({}, {
  --         prompt_title = "Harpoon",
  --         finder = require("telescope.finders").new_table {
  --           results = file_paths,
  --         },
  --         previewer = conf.file_previewer {},
  --         sorter = conf.generic_sorter {},
  --       })
  --       :find()
  --   end
  --   key.set("n", "<leader>ta", function()
  --     toggle_telescope(harpoon:list())
  --   end, { desc = "Open harpoon window" })
  -- end,
}
