return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "bash",
      "c",
      "css",
      "dockerfile",
      "gitignore",
      "hcl",
      "html",
      "javascript",
      "jinja",
      "jinja_inline",
      "jsdoc",
      "json",
      "python",
      "regex",
      "ruby",
      "rust",
      "solidity",
      "terraform",
      "tsx",
      "typescript",
      "xml",
      "yaml",
    },
  },
}
